eshop/cart_app/urls.py
from django.urls import path
from . import views

app_name = 'cart_app'
urlpatterns = [
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_details, name='cart_details'),
    path('cart_remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('remove_all/<int:product_id>/', views.remove_all, name='remove_all'),
]

eshop/eshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop', include('shop_app.urls')),
    path('search_app/', include('search_app.urls')),
    path('', include('cart_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/search_app/urls.py
from django.urls import path

from . import views

app_name='search_app'
urlpatterns = [
    path('search_app', views.search_result, name='search_result')
]

eshop/shop_app/urls.py
from django.urls import path


from . import views

app_name = 'shop_app'
urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/', views.prodetails, name='procatdetail'),
]

eshop/cart_app/models.py
from django.db import models
from shop_app.models import Products


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'cart'
        ordering = ['date_added',]

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quandity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def subtotal(self):
        return '{}'.format(self.product.price * self.quandity)

    def __str__(self):
        return '{}'.format(self.product)

eshop/search_app/models.py
from django.db import models

# Create your models here.

eshop/shop_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop_app:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Products(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop_app:procatdetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

eshop/cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop_app.models import Products
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Products.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quandity < cart_item.product.stock:
            cart_item.quandity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quandity=1, cart=cart)
        cart_item.save()
    return redirect('cart_app:cart_details')


def cart_details(request, counter=0, total=0, cart_items=None, ):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    cart_items = CartItem.objects.filter(cart=cart, active=True)
    try:
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quandity)
            counter += cart_item.quandity
    except Products.DoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter, ))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Products, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quandity > 1:
        cart_item.quandity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cart_details')


def remove_all(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Products, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_details')

eshop/search_app/views.py
from django.shortcuts import render
from shop_app.models import Products
from django.db.models import Q

# Create your views here.


def search_result(request):
    query = None
    product = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        product = Products.objects.all().filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request, 'search.html', {'query': query, 'products': product})

eshop/shop_app/views.py
# virtual environment = shop
from django.shortcuts import render, get_object_or_404
from .models import Category, Products
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.

# def index(request):
#     return render(request, 'index.html')
def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Products.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Products.objects.all().filter(available=True)
    pagiantor = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = pagiantor.page(page)
    except (EmptyPage, InvalidPage):
        products = pagiantor.page(pagiantor.num_pages)
    return render(request, "category.html", {'category': c_page, 'products': products})


def prodetails(request, c_slug, p_slug):
    try:
        product = Products.objects.get(category__slug=c_slug, slug=p_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

eshop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'CSS/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'CSS/custom.css' %}">
    <script src="https://kit.fontawesome.com/fc51e437b8.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metacondent %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
    <div class="container">
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
        {% include 'footer.html' %}
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

eshop/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block description %}
This is the cart page. proceed to place the order...
{% endblock %}
{% block title %}
Cart Page
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <h1>You have no Cart Items</h1><br>
        <p> Please Click <a href="{% url 'shop_app:allProdCat' %}">Here</a> to Shop... </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Cart</h1><br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="4">
                    Your Items
                </th>
            </tr>
            </thead>

            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="{{cart_item.product.name}}" class="float-left rounded custom_image"> </a>
                </td>
                <td class="text-left">
                    Name: {{cart_item.product.name}}<br>
                    Price: <b>₹</b>{{cart_item.product.price}}<br>
                    Qty: {{cart_item.quandity}} x ₹ {{cart_item.product.price}}
                </td>
                <td>
                    <b>₹</b> {{subtotal}}
                </td>
                {% if cart_item.quandity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-square-plus"></i></a><br>
                    <a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-square-minus"></i></a><br>
                    <a href="{% url 'cart_app:remove_all' cart_item.product.id %}"><i class="fa-sharp fa-solid fa-trash-can"></i></a><br>
                </td>
                {% else %}
                 <td><br>
                    &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-square-minus"></i></a><br>
                    &nbsp;<a href="{% url 'cart_app:remove_all' cart_item.product.id %}"><i class="fa-sharp fa-solid fa-trash-can"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            <tr>
                <td style=" background-color: #f8f9fa!important; text-align:right;">
                    <h4>Total: {{total}}</h4>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
<table class="table my_custom_table">
    <thead class="my_custom_thead">
    <tr>
        <th>
            Check Out
        </th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            Please review your shopping experience before making payment
        </td>
    </tr>
    </tbody>
</table>
    <div class="mx-auto">
        <a href="{% url 'shop_app:allProdCat' %}" class="btn btn-secondary btn-block my_custom_btn">Continue Shopping</a>
    </div>
</div>
</div>
{% endif %}
{% endblock %}

eshop/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block description %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        Welcome to VTS Business, Online Shop where you can buy all products
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}} -- VTS eshop
    {% else %}
        See Latest Collections -- VTS eshop
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx_auto">
                <p><a href="{% url 'shop_app:allProdCat' %}">Product Collection</a></p>
            </div>
        </div>
    </div>
    {% endif %}
    {% if category %}
<div>
    <div >
        <div>
            <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
        </div>
    </div>
</div>
    <br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
    </div>
    {% else %}
    <div>
        <img src="{% static 'image/banner.png' %}" alt="Our Products" height="250px" width="100%">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">Collection of Products</h1>
        <p class="text-justify">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. </p>
    </div>
    {% endif %}
<!--product display area-->
<div>
    <div>

        <div class="container">
            <div class="row">
                {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                  <div class="shadow-sm p-3 mb-5 bg-body-tertiary rounded">
                    <div class="card text-center" style="min-width:18rem min-height:20rem;">
                <a href="{{product.get_url}}"><img class="card-img-top" alt="{{product.name}}" src="{{product.image.url}}" style="width:100%px; height:300px"></a>

            <div class="card-body text-sie:14px text-transform:uppercase">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
                    </div><br>
                </div>
                    </div>
                {% endfor %}
            </div>
            <div class="mx-auto">
                {% if products.paginator.num_pages > 1 %}
                <hr>
                   <div class="text-center">
                     {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                    </div>
                {% endif %}
            </div>
            <br>
        </div>

    </div>
</div>
{% endblock %}

eshop/templates/footer.html
<div class="container-fluid">
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">@vts_business_online_shop private limited. All Right Reserved</p>
</div>
</div>

eshop/templates/header.html
{% load static %}
<br>
<div class="container">
<header>
    <center>
        <a href="{% url 'shop_app:allProdCat' %}"><img src="{% static 'image/logo.png' %}" alt="logo image" width="100" height="100"></a>
    </center>
</header>
</div>

eshop/templates/index.html
{% extends 'base.html' %}
{% block body %}

Hi, everybody how are you all
{% endblock %}

eshop/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="">E-shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'shop_app:allProdCat' %}">Home</a>
        </li>

        <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Products
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'shop_app:allProdCat' %}">All Products</a></li>
                {% for cat in links %}
                <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                {% endfor %}
            </ul>
      <li class="nav-item">
          <a class="nav-link" href="{% if item_count > 0 %} {% url 'cart_app:cart_details' %} {% endif %}">Your Cart <i class="fa-solid fa-cart-shopping">{% if item_count > 0 %}<sup> {{item_count}} </sup>{% endif %}</i></a>
        </li>

    </ul>
    <form class="d-flex" role="search" action="{% url 'search_app:search_result' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass fa-flip"></i></button>
    </form>
</div>

  </div>
</nav>

eshop/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block description %}
        {{product.description|truncatewords:155}}
{% endblock %}

{% block title %}

        {{product.name}} -- VTS eshop

{% endblock %}
{% block content %}
<div class="row my_pro_row">
    <div class="mx_auto">
        <p><a href="{% url 'shop_app:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-6 col-md-6 col-sm-6 col-lg-6 text-center">
        <div style="min-width: 18rem,">
            <img src="{{product.image.url}}" alt="{{product.name}}" style="width:100%;">
            <br>
        </div>
    </div>

    <div class="col-6 col-md-6 col-sm-6 col-lg-6 ">
        <div>
           <h1 class="prod_name">{{product.name}}</h1>
            <u><b><p>Product Description</p></b></u>
            <p class="text-justify">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p style="color:red"><b>Out of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary" style="--bs-btn-padding-x: 1.5rem" href="{% url 'cart_app:add_cart' product.id%}"><i class="fa-sharp fa-light fa-cart-shopping-fast">Add to Cart <i class="fa-solid fa-cart-shopping"></i></i></a>

            <a class="btn btn-primary" style="--bs-btn-padding-x: 1.5rem">Buy Now <i class="fa-solid fa-basket-shopping"></i></a>
            {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}

eshop/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block description %}
    We have verity of collection. Count on us...
{% endblock %}
{% block title %}
Search ...
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text>">you have searched for: <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem min-height:20rem;">
                <a href="{{product.get_url}}"><img class="card-img-top" alt="{{product.name}}" src="{{product.image.url}}" style="width:100%px; height:300px"></a>

             <div class="card-body text-sie:14px text-transform:uppercase">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
             </div>
            </div><br>

        </div>
        {% empty %}
            <div>
                <p class="text-center my_search_text" style="color:red"> Sorry! No results found</p>
            </div>
        {% endfor %}
    </div>
    <br>
</div>
{% endblock %}